name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-up-to-date:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch all branches
      run: git fetch --all

    - name: Check if the branch is up-to-date with base branch
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}
        git checkout ${{ github.event.pull_request.head.ref }}
        git merge --no-commit --no-ff origin/${{ github.event.pull_request.base.ref }} || echo "Out of date with base branch"
      continue-on-error: true

    - name: Check for conflicts with base branch
      run: |
        git merge --no-commit --no-ff origin/${{ github.event.pull_request.base.ref }}
      continue-on-error: true
