name: Check Branch Up-to-Date

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-branch-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Branch Up-to-Date
        run: |
          git fetch origin
          git rev-list --count --left-right origin/main...${{ github.head_ref }}
          if [ $? -eq 0 ]; then
            echo "Branch is up-to-date"
          else
            echo "Branch is out-of-date"
            exit 1
          fi
